version: '3'

services:
  web:
    build: .
    volumes:
      - dist:/usr/src/app/dist/AngularDockerExample
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - dist:/usr/share/nginx/html

volumes:
  dist:
